### PR TITLE
Updated Game file.

### PR DESCRIPTION
**Pull request by King-Del-ErnestO**
Hi, I changed a few lines of the game.py file and tried handling errors due to invalid user inputs. Please check it out. And let's also know when Dungeon 2.0 is coming out :)

### CODE REVIEW

**Comment by keivalya** [comment]
Yout code breaks immediately after
left>around

it should go further.

**Comment by King-Del-ErnestO** [comment]
Wowww! Just noticed the error, I'd work on it and send it back asap. I'm so sorry I didn't see that.

**Comment by keivalya** [comment]
It's fine. Take your time. @King-Del-ErnestO

**Comment by King-Del-ErnestO** [comment]
I've fixed it now. It was a simple indentation error. Sorryyy about that. Please try it now 😅 @keivalya

**Comment by keivalya** [comment]
Changes were great! Thanks for contributing 😄

**Comment by King-Del-ErnestO** [comment]
Thank You!!!

**Pull request merged**
