### PR TITLE
code and docs improved

### PR DESCRIPTION
**Pull request by Ujjawal179**

### CODE REVIEW

**Comment by keivalya** [comment]
Hey @Ujjawal179 
Hope you're doing good.

Honestly, yes your changes do improve the quality of my code. No doubt.
But, I cannot merge your PR just because you changed line using \n and cleaned it little at exit().

Those were really good inputs! I appreciate them. But, for the spirit of Open Source, I shall not merge them unless the major difference is made.

I really hope you understand.
All the very best. I've got more repos you can definitely work on!
Do consider having a look.

Happy learning!😄

**Comment by Ujjawal179** [comment]
what could i do to merge my pr?

**Comment by keivalya** [comment]
@Ujjawal179 
You can make more quality PRs such as in README file. It can "always" get better.

In the code, you can add a longer story but you'll have to be careful such that you don't disrupt other code. It will be quite tricky the way code has become little more complicated. Yet, you can try.

Otherwise, if you need any help, you can connect to me on my LinkedIn [Keivalya](https://www.linkedin.com/in/keivalya) OR DM me on my IG: **keivalya**

I'll be more than happy to help you.
For now, just check your Hacktoberfest profile. I'll merge this one, you're welcomed to contribute to my other repositories. If you wish to, just let me know so I can label them "Hacktoberfest"

**Comment by Ujjawal179** [comment]
Thanks bro for helping me. Currently I am only 15 years old and learning advanced python. I will try my best to complete hacktoberfest challenge.
Unfortunately, I don't use Linkedin or IG

**Comment by keivalya** [comment]
@Ujjawal179 
No issues at all! It's really inspiring how you are into programming sinch such a young age!!
Keep going. Anytime you need any help, feel free to contact me.

All the very best for Hacktoberfest as well as life!🌱

**Pull request merged**
